---
apiVersion: v1
kind: Namespace
metadata:
  name: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  namespace: backend
  labels:
    app: auth-service
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
        tier: backend
    spec:
      containers:
        - name: auth-service
          image: 449629806828.dkr.ecr.me-central-1.amazonaws.com/ms-auth-service@sha256:9f9cfd67ba6ce59f10c2c40d218f289212efe066f081578a5a6ac8422f514337
          ports:
            - containerPort: 8201
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: backend
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /ms-auth-server-1-0/actuator/health
spec:
  type: NodePort
  selector:
    app: auth-service
  ports:
    - name: auth
      protocol: TCP
      port: 8201
      targetPort: 8201