---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-deployment
  namespace: backend
  labels:
    app: core-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: core-service
  template:
    metadata:
      labels:
        app: core-service
        tier: backend
    spec:
      containers:
        - name: core-service
          image: 449629806828.dkr.ecr.me-central-1.amazonaws.com/core-services:latest
          ports:
            - containerPort: 9099
---
apiVersion: v1
kind: Service
metadata:
  name: core-service
  namespace: backend
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /core-service-1-0/actuator/health
spec:
  type: NodePort
  selector:
    app: core-service 
  ports:
    - name: core
      protocol: TCP
      port: 9099
      targetPort: 9099
