---
apiVersion: v1
kind: Namespace
metadata:
  name: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cron-deployment
  namespace: backend
  labels:
    app: cron-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cron-service
  template:
    metadata:
      labels:
        app: cron-service
        tier: backend
    spec:
      containers:
        - name: cron-service
          image: 449629806828.dkr.ecr.me-central-1.amazonaws.com/cron-service:latest
          ports:
            - containerPort: 9099
---
apiVersion: v1
kind: Service
metadata:
  name: cron-service
  namespace: backend
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /cron-service-1-0/actuator/health
spec:
  type: NodePort
  selector:
    app: cron-service
  ports:
    - protocol: TCP
      port: 9099
      targetPort: 9099
