---
apiVersion: v1
kind: Namespace
metadata:
  name: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dao-deployment
  namespace: backend
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dao-service
  template:
    metadata:
      labels:
        app: dao-service
        tier: backend
    spec:
      containers:
        - name: dao-service
          image: 449629806828.dkr.ecr.me-central-1.amazonaws.com/dao-service:latest
          ports:
            - containerPort: 8100
---
apiVersion: v1
kind: Service
metadata:
  name: dao-service
  namespace: backend
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /dao-service-1-0/actuator/health
spec:
  type: NodePort
  selector:
    app: dao-service
  ports:
    - name: dao
      protocol: TCP
      port: 8100
      targetPort: 8100