---
apiVersion: v1
kind: Namespace
metadata:
  name: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-deployment
  namespace: backend
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kafka-service
  template:
    metadata:
      labels:
        app: kafka-service
        tier: backend
    spec:
      containers:
        - name: core-service
          image: 449629806828.dkr.ecr.me-central-1.amazonaws.com/kafka-service:latest
          ports:
            - containerPort: 9010
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: backend
spec:
  type: NodePort
  selector:
    app: kafka-service
  ports:
    - protocol: TCP
      port: 9010
      targetPort: 9010