---
apiVersion: v1
kind: Namespace
metadata:
  name: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otp-deployment
  namespace: backend
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: otp-service
  template:
    metadata:
      labels:
        app: otp-service
        tier: backend
    spec:
      containers:
        - name: otp-service
          image: 449629806828.dkr.ecr.me-central-1.amazonaws.com/otp-service:latest
          ports:
            - containerPort: 8102
---
apiVersion: v1
kind: Service
metadata:
  name: otp-service
  namespace: backend
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /ms-otp-service-1-0/actuator/health
spec:
  type: NodePort
  selector:
    app: otp-service
  ports:
    - protocol: TCP
      port: 8102
      targetPort: 8102
