---
apiVersion: v1
kind: Namespace
metadata:
  name: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-deployment
  namespace: backend
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: portal-service
  template:
    metadata:
      labels:
        app: portal-service
        tier: backend
    spec:
      containers:
        - name: portal-service
          image: 449629806828.dkr.ecr.me-central-1.amazonaws.com/ms-portal:latest
          ports:
            - containerPort: 8008
---
apiVersion: v1
kind: Service
metadata:
  name: portal-service
  namespace: backend
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /ms-portal-1-0/actuator/health/actuator/health
spec:
  type: NodePort
  selector:
    app: portal-service
  ports:
    - protocol: TCP
      port: 8008
      targetPort: 8008